# Generated by Django 4.2.5 on 2023-10-03 15:01

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("photos", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ExpiringLink",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                ("link", models.CharField(blank=True, max_length=255)),
                ("expired_at", models.DateTimeField(blank=True)),
                (
                    "image",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="expiring_link",
                        to="photos.photo",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
