# Generated by Django 4.2.5 on 2023-10-05 13:22

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("photos", "0003_alter_expiringlink_image"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="expiringlink",
            options={"ordering": ("-created",)},
        ),
    ]
